services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_PASSWORD=${DB_LOCAL_PASSWORD}'
      - 'POSTGRES_USER=${DB_LOCAL_USERNAME}'
    ports:
      - '5432:5432'
